name: despliegue_remoto self-hosted runner
on:
  push:
    branches:
      - main # O la rama que desees
jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Copiar código
        uses: actions/checkout@v3

      - name: Añadir clave SSH al agente
        uses: webfactory/ssh-agent@v0.4.1
        with:
         ssh-private-key: ${{secrets.SSH_PRIVATE_KEY_JALS}} # Clave privada

      - name: Conectar y ejecutar comandos en el servidor
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST_JALS}} # Tu nombre de host
          username: ${{secrets.SSH_USERNAME_JALS}} # nombre de usuario
          key: ${{secrets.SSH_PRIVATE_KEY_JALS}} # Clave privada
          script: |
            echo "### path servidor JALS ###"
            
            pwd
            ls -lrt 
            echo '### fin del workflow ###'
